'use client'

import { useState } from 'react'
import Head from 'next/head'
import axios from 'axios'
import styles from './styles/Home.module.css'

export default function Home() {

  const [subreddit, setSubreddit] = useState()
  const [keyword, setKeyword] = useState()
  const [validate, setValidate] = useState(null)
  const [posts, setPosts] = useState()

  const search = async (e) => {
    e.preventDefault()
    setValidate(null)
  
    if (!subreddit) {
      setValidate('Enter a subreddit')
    } 
    
    else if (!keyword) {
      setValidate('Enter a keyword')
    } 
    
    else {

      // const server = process.env.NEXT_PUBLIC_SERVER_ROOT

      try {
        const response = await axios.get(`http://localhost:8080/scanner/${subreddit}/${keyword}`)
        setPosts(response.data)
      } 
      
      catch (error) {
        console.error('Error fetching data:', error)
      }
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Reddit Mood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Reddit Mood
        </h1>

        {validate && <div className={styles.validate}>{validate}</div>}
        {!validate && <div className={styles.info}>See how people are feeling at r/

        <span className={styles.highlight}>{subreddit ? subreddit : 'aSubreddit'}</span>
        {' '}about{' '}
        <span className={styles.highlight}>{keyword ? keyword : 'something'}</span></div>}

        <form onSubmit={search}>
          <p className={styles.description}>
            Scan {' '}
            <input className={styles.code} type="text" placeholder="subreddit" onChange={(e) => setSubreddit(e.target.value)} />
            {' '} for {' '}
            <input className={styles.code} type="text" placeholder="keyword" onChange={(e) => setKeyword(e.target.value)} />
            <button className={styles.button} onClick={search} type="submit">Go</button>
          </p>
        </form>

      </main>
    </div>
  )
}
